use GENY_DATA;
LOAD DATA LOCAL INFILE <<FILE_NAME_FULL_PATH>> 
INTO TABLE  <<TABLE_NAME>>
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
SHOW WARNINGS


example : 
use GENY_DATA;
LOAD DATA LOCAL INFILE '/home/farouk/web_robot/STATS/WEB_DATA_STATS.csv' 
INTO TABLE  WEB_DATA_STATS
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
delete from WEB_DATA_STATS where DT < '2015-01-01';
SHOW WARNINGS