USE GENY_DATA;

DROP TABLE IF EXISTS RACES;
CREATE TABLE RACES
(
	DT DATE,
	RACE_ID INT,
	H_DEPART TIME,
	NB_GREP INT,
	HYPPO VARCHAR(200),
	NB_RACE INT,
	R_NAME VARCHAR(200),
	TYPE_C VARCHAR(100),
    SPECIALITE VARCHAR(100),
	COURSE VARCHAR(100),
    categorie VARCHAR(100),
	CORDE VARCHAR(20),
	PRIZE FLOAT,
	R_LENGHT INT,
	TERRAIN VARCHAR(100),
	ET_GAZON FLOAT,
	PISTE VARCHAR(100),
	SPEC VARCHAR(100),
	ELIGIBLES VARCHAR(1000),
	STAT_LNK VARCHAR(500),
	RSLT_LNK VARCHAR(500),
	COTE_LNK VARCHAR(500),
    CSAQ_LNK VARCHAR(500),
	DETAILS_COURSE VARCHAR(2000),
    PRIMARY KEY (RACE_ID)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ID ON RACES (RACE_ID);

DROP TABLE IF EXISTS RACE_HORSES;
CREATE TABLE RACE_HORSES
(
	DT DATE NOT NULL,
	RACE_ID INT NOT NULL,
	HORSE VARCHAR(100),
	HORSE_ID INT NOT NULL,
	OEIL VARCHAR(100),
	POS_DEPART INT NOT NULL,
	HR_LENGTH INT NULL DEFAULT NULL,
	IRON_REMOV VARCHAR(10),
	DECHARGE FLOAT NULL DEFAULT NULL,
	SEX VARCHAR(5),
	AGE INT NULL DEFAULT NULL,
	WEIGHT FLOAT NULL DEFAULT NULL,
    DRIVER VARCHAR(100),
    DRIVER_ID INT NULL DEFAULT NULL,
    COACH VARCHAR(100),
    COACH_ID INT NULL DEFAULT NULL,
	MUSIC VARCHAR(200),
    WINNING INT NULL DEFAULT NULL,
    VALEUR FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (RACE_ID, HORSE_ID)
    
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ID ON RACE_HORSES (RACE_ID, HORSE_ID);

DROP TABLE IF EXISTS RACE_RESULTS;
CREATE TABLE RACE_RESULTS
(
	DT DATE NOT NULL,
	RACE_ID INT NOT NULL,
    POS_DEPART INT NOT NULL,
    HORSE VARCHAR(100),
	RANK INT NULL DEFAULT NULL,
    FAIL VARCHAR(10),
    UNIT_TIME FLOAT NULL DEFAULT NULL,
    VISUAL_GAP VARCHAR(20),
    PRIMARY KEY (RACE_ID, POS_DEPART)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ID ON RACE_RESULTS (RACE_ID, POS_DEPART);


DROP TABLE IF EXISTS RACE_COTES;
CREATE TABLE RACE_COTES
(
	DT DATE NOT NULL,
	RACE_ID INT NOT NULL,
    POS_DEPART INT NOT NULL,
    HORSE VARCHAR(100),
	COTE_30mn FLOAT NULL DEFAULT NULL,
	COTE_F FLOAT NULL DEFAULT NULL,
	EVOL INT NULL DEFAULT NULL,
	RATIO_30mn FLOAT NULL DEFAULT NULL,
	RATIO_F FLOAT NULL DEFAULT NULL,
    PRIMARY KEY (RACE_ID, POS_DEPART)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ID ON RACE_COTES (RACE_ID, POS_DEPART);


DROP TABLE IF EXISTS RACE_CASAQUES;
CREATE TABLE RACE_CASAQUES
(
	DT DATE,
    RACE_ID INT,
    H_POS INT,
    H_NAME VARCHAR(100),
    LNK VARCHAR(500),
    PRIMARY KEY (RACE_ID, H_POS)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ID ON RACE_CASAQUES (RACE_ID, H_POS);
